use_frameworks!

target 'IDMFoundation_Example' do
  pod 'IDMFoundation', :path => '../'
#  pod 'IDMFoundation/MBProgressHUD', :path => '../'
  pod 'IDMFoundation/Reachability', :path => '../'
  pod 'IDMFoundation/JGProgressHUD', :path => '../'
  pod 'IDMFoundation/CameraAsset', :path => '../'
  pod 'IDMFoundation/ObjectMapper', :path => '../'
#  pod 'IDMFoundation/RequestParameter', :path => '../'
#  pod 'IDMFoundation/DKAsset', :path => '../'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
#  pod 'SwinjectPropertyLoader'
  pod 'SwinjectStoryboard'
end
