use_frameworks!

target 'IDMFoundation_Example' do
  pod 'IDMFoundation', :path => '../'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
#  pod 'SwinjectPropertyLoader'
  pod 'SwinjectStoryboard'
end
