use_frameworks!

target 'IDMFoundation_Example' do
  pod 'IDMFoundation', :path => '../'
#  pod 'IDMFoundation/MBProgressHUD', :path => '../'
  pod 'IDMFoundation/Reachability', :path => '../'
  pod 'IDMFoundation/Loading', :path => '../'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
#  pod 'SwinjectPropertyLoader'
  pod 'SwinjectStoryboard'
end
